#pragma once

#define MAX_INPUT_CHAR_SIZE 256
#define MAX_FILE_NAME_SIZE 80

#define MAX_TABLE_NAME_SIZE 31
#define MAX_COLUMN_NAME_SIZE 31
#define MAX_INDEX_NAME_SIZE 31
#define MAX_INDEX_TYPE_NAME_SIZE 16
#define MAX_TYPE_NAME_SIZE 15
#define MAX_RESOLVED_TYPE_NAME_SIZE 20
#define MAX_VARCHAR_VALUE_SIZE 255
#define MAX_CHAR_VALUE_SIZE 128
#define MAX_BINARY_VALUE_SIZE 128
#define MAX_COLUMNS_PER_TABLE 16
#define MAX_COLUMNS_IN_SELECT 16
#define MAX_WHERE_CONDITIONS 8

#define MAX_TABLE_INDEX_COUNT 8
#define MAX_INDEX_COLUMN_COUNT 4
#define MAX_INDEX_KEY_PART_SIZE 255
